### ISSUE TITLE
ошибка в видеоотеке неврус

### ISSUE THREAD

**Issue by weter71** [technic/iptvdream#1]
в видеотеку входит, по фаворитам можно лазить а при запуске какого либо фильма получаем ошибку

poll: unhandled POLLERR/HUP/NVAL for fd 83(16)
action ->  OkCancelActions ok
[KartinaTV] ok pressed. type 1 file 8
[KartinaTV] bouquet In 8 0
[KartinaTV] NewrusMovies: Getting getting video info 8
add fid 8 to bouquet
hide %s
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2462, in ok
    self.fillSingle()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2244, in fillSingle
    self.selectionChanged()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2319, in selectionChanged
    self.updateInfo()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2353, in updateInfo
    self["year"].setText(ktv.videos[cid].year)
  File "/usr/lib/enigma2/python/Components/VariableText.py", line 12, in setText
    self.instance.setText(self.message or "")
TypeError: in method 'eLabel_setText', argument 2 of type 'std::string const &'
(PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x2640c88>>,('OkCancelActions', 'ok')) failed)
]]>
        </enigma2crashlog>
        <pythonMD5sum>

**Comment by technic** [comment]
должно быть исправлено 2.3.7

**Comment by weter71** [comment]
все пошло, спасибо

**Comment by technic** [comment]
отлично.

**Comment by weter71** [comment]
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 104, in save
    self.run()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 108, in run
    plugin(session=self.session)
  File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in **call**
    return self.fnc(_self.args + args, *_newkwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 466, in AOpen
    runManager.run(aname)
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 335, in run
    self.open()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 347, in open
    self.session.open(KartinaVideoPlayer)
  File "/usr/lib/enigma2/python/mytest.py", line 313, in open
    self.execBegin()
  File "/usr/lib/enigma2/python/mytest.py", line 207, in execBegin
    c.execBegin()
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 97, in execBegin
    x()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 641, in start
    if not self.go():
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 671, in go
    self.doGo()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 1219, in doGo
    self.showList()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 1210, in showList
    self.session.openWithCallback(self.showListCB, KartinaVideoList)
  File "/usr/lib/enigma2/python/mytest.py", line 296, in openWithCallback
    dlg = self.open(screen, _arguments, *_kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 313, in open
    self.execBegin()
  File "/usr/lib/enigma2/python/mytest.py", line 207, in execBegin
    c.execBegin()
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 97, in execBegin
    x()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2175, in start
    self.fillList()  
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2218, in fillList
    self.selectionChanged()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2320, in selectionChanged
    self.updateInfo()
  File "/usr/lib/enigma2/python/Plugins/Extensions/KartinaTV/plugin.py", line 2351, in updateInfo
    self["rate1"].setValue(ktv.videos[cid].rate_imdb)
AttributeError: Video instance has no attribute 'rate_imdb'                                                                                                                                                                                                                                                                                                                                на амико на ап/п имедже не как не хотит работать видеотека, посматри техник.

**Comment by technic** [comment]
нуу вы смержили как положено всё ?

**Comment by weter71** [comment]
да

**Comment by technic** [comment]
работает

**Comment by weter71** [comment]
спасибо, попробуем
